config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :events
  resources :calendars
  resources :blogposts

  get 'about',              to: 'static_pages#about'
  get 'mitmischen',         to: 'static_pages#mitmischen'
  get 'kontakt',            to: 'static_pages#kontakt'
  get 'nussletter',         to: 'static_pages#newsletter'
  get 'satzung',            to: 'static_pages#satzung'
  get 'mitgliedsformular',  to: 'static_pages#mitgliedsformular'
  get 'impressum',          to: 'static_pages#impressum'
  get 'presse',             to: 'static_pages#presse'

  root 'static_pages#home'
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  include ImageUploader::Attachment(:image)
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :slug

  belongs_to :user

  def get_display_name
    if display_name.present?
      display_name
    else
      user.name
    end
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]

  def index
    @blogposts = Blogpost.all.reverse
  end

  def show; end

  def new
    @blogpost = Blogpost.new
  end

  def edit
  end

  def create
    @blogpost = Blogpost.new(blogpost_params)
    @blogpost.user = current_user

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :description, :display_name, :published_at, :image, :remove_image)
    end

end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
  def show_date(blogpost)
    if blogpost.published_at.present?
      blogpost.published_at.strftime("%d %b %Y")
    end    
  end
end

app/views/blogposts/_form.html.haml
= form_for @blogpost do |f|
  = render "error_messages", target: @blogpost
  - if @blogpost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blogpost.errors.count, "error")} prohibited this blogpost from being saved:"
      %ul
        - @blogpost.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title, placeholder: "Ein Titel, der Beine macht"
  .field
    = f.label :description
    = f.text_area :description, placeholder: "Lass hier die Knorken knallen."
  .field
    = f.label :display_name
    = f.text_field :display_name, placeholder: "Wenn leer, dann username (da staunste?)"
  .field
    = f.label :published_at
    = f.datetime_select :published_at
  .field
    = f.label :image
    = f.file_field :image
  - if @blogpost.image_data?
    .field
      = image_tag @blogpost.image_url(:small)
    .field
      Remove attachment: #{f.check_box :remove_image}

  .actions
    = f.submit 'Save'

app/views/blogposts/edit.html.haml
%h1 Editing blogpost

= render 'form'

= link_to 'Show', @blogpost
\|
= link_to 'Back', blogposts_path

app/views/blogposts/index.html.haml
%h1.spacer-m
  Bloggen und Posten

.row
  .col-md-10.col-md-offset-1.blog
    %ul.blog-list
      - @blogposts.each do |blogpost|
        %li
          %h2
            = link_to blogpost.title, blogpost
          %p
            = show_date(blogpost)
            von
            = blogpost.get_display_name
          = image_tag blogpost.image_url(:medium), class: "blog__image" if blogpost.image.present?
          %p= markdown blogpost.description
          %p ***

app/views/blogposts/new.html.haml
%h1 New blogpost

= render 'form'

= link_to 'Back', blogposts_path

app/views/blogposts/show.html.haml
%p#notice= notice

%article.blog
  %h1.spacer-m
    = @blogpost.title
  .center-text
    %p
      = show_date(@blogpost)
      von
      = @blogpost.get_display_name
      %br
      = image_tag @blogpost.image_url(:medium), class: "blog__image" if @blogpost.image.present?

    %p
      = markdown @blogpost.description

    %p
      ***
  - if user_signed_in?
    = link_to 'Edit', edit_blogpost_path(@blogpost)
    \|
    = link_to 'Destroy', @blogpost, method: :delete, data: { confirm: 'Are you sure?' }
    \|
  = link_to 'Back', blogposts_path