config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :events
  resources :calendars
  resources :blogposts

  get 'about',              to: 'static_pages#about'
  get 'mitmischen',         to: 'static_pages#mitmischen'
  get 'kontakt',            to: 'static_pages#kontakt'
  get 'nussletter',         to: 'static_pages#newsletter'
  get 'satzung',            to: 'static_pages#satzung'
  get 'mitgliedsformular',  to: 'static_pages#mitgliedsformular'
  get 'impressum',          to: 'static_pages#impressum'
  get 'presse',             to: 'static_pages#presse'

  root 'static_pages#home'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :calendar
  scope :not_yet_happened, -> { where('start_time >= ?', Date.current) }
  serialize :recurring, Hash

  has_many :event_exceptions

  def recurring=(value)
    return super(nil) unless real_valid_rule?(value)
    super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
  end

  def rule
    IceCube::Rule.from_hash recurring
  end

  def schedule(start)
    schedule = IceCube::Schedule.new(start)
    schedule.add_recurrence_rule(rule)
    schedule
  end

  def calendar_events(start)
    if recurring.empty?
      [self]
    else
      end_date = start.end_of_month.end_of_week
      schedule(start_time).occurrences(end_date).map do |date|
        Event.new(id: id, name: name, start_time: date)
      end
    end
  end

  private

  def real_valid_rule?(value)
    return false unless RecurringSelect.is_valid_rule?(value)
    return false if  value == "null"
    true
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.not_yet_happened.order("start_time ASC")
    @hoc_events = Calendar.find(1).events
  end

  def show
    begin
      @time = Time.parse(params[:time])
    rescue
      @time = @event.start_time
    end
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_time, :end_time, :recurring, :location, :location_url, :calendar_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper

  def prettify(event)
    @formats = []
    @formats << event.start_time.strftime("%d %b %Y")
    @formats << event.start_time.strftime("%R")
    @formats << event.end_time.strftime("%d %b %Y")
    @formats << event.end_time.strftime("%R")
  end
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name, placeholder: "Was zum Interessieren"
  .field
    = f.label :description
    = f.text_area :description, placeholder: "Was zum Mund wässrig machen"
  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :recurring
    = f.select_recurring :recurring
  .field
    = f.label :location
    = f.text_field :location, placeholder: "Adresse oder virtuell oder bei dir in der Küche?"
  .field
    = f.label :location_url
    = f.text_field :location_url, placeholder: "Please ne URL hier"
  .field
    = f.collection_select(:calendar_id, Calendar.where.not(name: "Alle Events"), :id, :name, prompt: "Select a Calendar")
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1.spacer-m
  Zückt die Kalender!

#eventlist
- @hoc_events.each do |event|
  .center-text
    %h2.spacer-s
      = link_to event.name, event_path(event.id, time: event.start_time)
    %p
      - if event.recurring?
        = event.rule.to_s
        ·
      = event.location
    %p
      - if event.description?
        = event.description
    %p.spacer-s
      - if user_signed_in?
        %br
        = link_to 'Edit', edit_event_path(event)
        \|
        = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
    %p.spacer-m
      *

- if user_signed_in?
  %p
    = link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

.center-text
  %h1 
    = @event.name
  %p
    - if @event.location_url?
      %a{href: @event.location_url}
        = @event.location
    - else
      = @event.location
  %p
    - if @event.recurring?
      = @event.rule.to_s
    - else
      %b
        = prettify(@event)[0]
    um
    %strong
      = prettify(@event)[1]

    bis
    - if prettify(@event)[0] != prettify(@event)[2]
      %strong
        = prettify(@event)[2]
      um
    %strong
      = prettify(@event)[3]
  %p.spacer-m
    = @event.description
  %p
    Im Kalender
    = link_to "#{@event.calendar.name}", calendar_path(@event.calendar)

  %p
    - if user_signed_in?
      = link_to 'Edit', edit_event_path
      \|
      = link_to "Delete", event_path(@event), method: :delete
      %br
    = link_to 'All Events', events_path