config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :events
  resources :calendars
  resources :blogposts

  get 'about',              to: 'static_pages#about'
  get 'mitmischen',         to: 'static_pages#mitmischen'
  get 'kontakt',            to: 'static_pages#kontakt'
  get 'nussletter',         to: 'static_pages#newsletter'
  get 'satzung',            to: 'static_pages#satzung'
  get 'mitgliedsformular',  to: 'static_pages#mitgliedsformular'
  get 'impressum',          to: 'static_pages#impressum'
  get 'presse',             to: 'static_pages#presse'

  root 'static_pages#home'
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :events
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_calendar, except: [:index, :new]

  # GET /calendars
  def index
  end

  # GET /calendars/1
  def show
    @other_calendars = Calendar.where.not(id: @calendar.id)
    if @calendar.show_all_events?
      @events = Event.all.flat_map do |event|
        event.calendar_events(params.fetch(:start_time, Time.current).to_date)
      end
    else
      @events = @calendar.events.flat_map do |event|
        event.calendar_events(params.fetch(:start_time, Time.current).to_date)
      end
      @future_events = @calendar.events.not_yet_happened.flat_map do |event|
        event.calendar_events(params.fetch(:start_time, Time.current).to_date)
      end
    end
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:name)
    end
end

app/views/calendars/_form.html.haml
= form_for @calendar do |f|
  - if @calendar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@calendar.errors.count, "error")} prohibited this calendar from being saved:"
      %ul
        - @calendar.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/calendars/edit.html.haml
%h1 Editing calendar

= render 'form'

= link_to 'Show', @calendar
\|
= link_to 'Back', calendars_path

app/views/calendars/index.html.haml
%h1.spacer-m
  Kalender hier Kalender da


%ul.spacer-m.calender-list
  - Calendar.all.each do |calendar|
    %li
      = link_to calendar.name, calendar

app/views/calendars/new.html.haml
%h1 New calendar

= render 'form'

= link_to 'Back', calendars_path

app/views/calendars/show.html.haml
.calendar.spacer-m
  .big
    = month_calendar events: @events do |date, events|
      = date.day
      %br
      - events.each do |event|
        = link_to event.name, event_path(event)
  .smol
    .simple-calendar
      .calendar-heading
        %span.calendar-title
          = @calendar.name
      - @future_events&.each do |event|
        = link_to event.name, event_path(event)
        %br
        .fine
          = prettify(event)[0] 
          @
          = prettify(event)[1]
        = event.description
        %br *

.center-text
  %p= link_to 'All calendars', calendars_path