config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :events
  resources :calendars
  resources :blogposts

  get 'about',              to: 'static_pages#about'
  get 'mitmischen',         to: 'static_pages#mitmischen'
  get 'kontakt',            to: 'static_pages#kontakt'
  get 'nussletter',         to: 'static_pages#newsletter'
  get 'satzung',            to: 'static_pages#satzung'
  get 'mitgliedsformular',  to: 'static_pages#mitgliedsformular'
  get 'impressum',          to: 'static_pages#impressum'
  get 'presse',             to: 'static_pages#presse'

  root 'static_pages#home'
end

app/views/layouts/_footer.html.haml
.container.footer-wrapper
  .row.spacer-s
    .col-sm-7
      %h3 Anderswo
      %ul.blank-list
        %li= link_to "Mastodon @heartofcode", "https://systemli.social/@heartofcode", rel: "me", title: "Mastodon"
        %li= link_to "Twitter @heartofcode", "https://twitter.com/heartofcode", title: "Twitter"
        %li= link_to "GitHub @heartsofcode", "https://github.com/heartsofcode/hoc_home", title: " GitHub"

    .col-sm-3
      %h3 Vereinskrams
      %ul.blank-list
        %li= link_to "Satzung", satzung_path()
        %li= link_to "Mitglitzerformular", mitgliedsformular_path()

    .col-sm-2
      %h3 Mitglitzer
      - if  user_signed_in?
        = link_to "Log out", destroy_user_session_path, method: :delete
      - else
        %ul.blank-list
          %li
            = link_to "Log in", new_user_session_path
  .row
    %p.col-sm-12
      ©
      = Time.now.year
      Heart of Code e.V.

app/views/layouts/_glitter-nav.html.haml
%nav.glitter-nav
  .dropdown
    .nav-item.dropdown-toggle{id: "dropdownUser",
                         data: {toggle: "dropdown"},
                         aria: {haspopup: "true",
                         expanded: "false"}}
      👩‍🚀 Ahoi,
      =current_user.email
    .dropdown-menu{aria:{labelledby: "dropdownUser"}}
      = link_to '🔩 Edit profile', edit_user_registration_path, class: 'dropdown-item'
      = link_to "🍃 Log out", destroy_user_session_path, method: :delete, class: 'dropdown-item'

  .dropdown
    .nav-item.dropdown-toggle{id: "dropdownNew",
                              data: {toggle: "dropdown"},
                              aria: {haspopup: "true",
                              expanded: "false"}}
      ✨ Neu
    .dropdown-menu{aria: {labelledby: "dropdownNew"}}
      %ul
        %li= link_to "✨ Neuer Blogpost", new_blogpost_path
        %li= link_to "✨ Neues Event", new_event_path

app/views/layouts/_navigation.html.haml
%header
  - if user_signed_in?
    = render "layouts/glitter-nav"

  %nav.nav
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only toggle menu
        %span 🍔
    #navbarCollapse.collapse.navbar-collapse
      %ul.navigation
        %li= link_to "about", about_path
        %li= link_to "kalender", calendar_path(1)
        %li
          = link_to root_path, title: "Heart of Code Startseite", class: "logo" do
            = image_tag "heartofcode42.jpg", id:"logo", alt: "Heart of Code Logo"
        %li= link_to "blog", blogposts_path
        %li= link_to "kontakt", kontakt_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "zpoxxz", :name => "flattr:id"}/
    %meta{charset: "utf-8"}

    = render 'application/favicon'

    %title Heart of Code

    = csrf_meta_tags
    %meta{:content => "", :name => "description"}/
    %meta{:content => "Heart of Code", :name => "author"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{href: "https://fonts.googleapis.com/css?family=Josefin+Sans:400,600", :rel => "stylesheet", :type => "text/css"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navigation'

    %main.content-main-wrapper
      - if notice || alert
        .container
          - if notice
            %div.alert.alert-success
              %p= notice
              %button.close-flash
                .sr-only close alert
                X
          - if alert
            %div.alert.alert-danger
              %p= alert
              %button.close-flash
                .sr-only close alert
                X

      .row.content
        .container
          = yield

    %footer.footer
      = render 'layouts/footer'

app/views/layouts/event.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "zpoxxz", :name => "flattr:id"}/

    = csrf_meta_tags
    %meta{:content => "", :name => "description"}/
    %meta{:content => "Heart of Code", :name => "author"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{href: "https://fonts.googleapis.com/css?family=Inconsolata:400,700|Josefin+Sans:400,100,300,600,700|Annie+Use+Your+Telescope|Schoolbell|Sue+Ellen+Francisco|Just+Me+Again+Down+Here|Roboto:100,300,400,500|Roboto+Mono:400,100,300,500,700|Open+Sans+Condensed:300", :rel => "stylesheet", :type => "text/css"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container= render 'layouts/navigation'

    .container.content-main-wrapper
      .content.row.tagline
        .col-lg-12.text-center
          %a{href: "/", :title => "…the most beautiful and revolutionary ship ever built."}
            = image_tag "heartofcode42.jpg", id:"logo"
      .row.content
        .container
          = yield

  %footer
    .content.container= render 'layouts/footer'